version: "3"
services:
  crow_server:
    build:
      context: ./cppbox
      dockerfile: Dockerfile
    volumes:
        - ./cppbox/crow_server/public:/usr/src/crow_server/public
    environment: 
        - PORT=8080
    ports: 
        - 8080:8080
      